#version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy

    ports:
      - "80:80"

    volumes:
      - ./nginx/nodeapp.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  app:
    image: peterdeag/nodejs-mysql-crud:latest
    container_name: node-app

    expose:
      - "3000"

    depends_on:
      - paystand-mysql

    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  paystand-mysql:
    image: mysql:5.7

    container_name: paystand-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - ./database:/docker-entrypoint-initdb.d
